### PR TITLE
Fix Go Module Name

### PR DESCRIPTION
**Pull request by euriostigue**
### What
 - Adds some `additionalProperties: false` requirements where I noticed this made sense. This isn't an exhaustive fix to the schema.
 - Commits all file changes from `ruby generate.rb`
 - Adds the repository names to the `openapi generate` command. This allows Go client & server code to be used as modules.
 - Changes the `effx_api_v2.yaml` path declaration to be relative. This allows you to fetch the YAML file as a GET request: ex `http://localhost:8080/effx_api_v2.yaml`

### CODE REVIEW

**Review by weeyum — APPROVED** [review]
makes sense - can we however change it from `link_groups` to `linkGroups` to make it consistent? also do we know if camelCase vs snake_case matters for marshaling?

**Comment by euriostigue** [comment]
> makes sense - can we however change it from `link_groups` to `linkGroups` to make it consistent? also do we know if camelCase vs snake_case matters for marshaling?

The marshaling honors the `json` tags which are case-sensitive. The tags replicate the naming conventions we choose.

Should I update all variables to use camelCase?

**Comment by weeyum** [comment]
if we honor the tags, then I think in the past we've use snake case. in either case (haha) let's just make sure it's consistent. I slightly prefer camelCase here just because it matches our graphql schema casing, so it might make copying things (with copier) easier down the road?

**Comment by euriostigue** [comment]
camelCase makes sense to me!

**Pull request merged**
